spring:
  application:
    name: intershop

  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://postgres:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  liquibase:
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://postgres:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

app:
  image-file-base-path: ${INTERSHOP_ITEM_IMG_DIR}
  payments:
    service:
      url: ${APP_PAYMENTS_SERVICE_URL:http://localhost:8081}

cache:
  ttl:
    item: 60
    items-page: 30


#
#
#logging:
#  level:
#    root: DEBUG
#    web: DEBUG
#    sql: DEBUG
